### ISSUE TITLE
Add new `wp_get_normalized_script_args()` helper method in `WP_Scripts` API that handles new `$args` and legacy `$in_footer` parameters

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#10]
## Description
With the introduction of the new `$args` parameter to the `wp_register_script` and `wp_enqueue_script` functions (as an override to the legacy `$in_footer` parameter) it is necessary to introduce a normalization helper method that accepts both the old and new format/type of data applied during script registration, and normalizes the data in a consistent and common format.

Further additions to/modifications within the `WP_Scripts` API as part of the ongoing loading strategy work will utilize this normalized data to achieve the intended outcome. 

## Acceptance Criteria

* Creation of a new `wp_get_normalized_script_args()` helper method within the `WP_Scripts` class/API. The current WP_Scripts API resides in source [at this location](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-scripts.php).
* This new method is to be a private method, as it only needs to be called internally amongst other `WP_Scripts` class methods. 
* This method will return (normalized) data for said registered script object, and this data will be stored at the time of script registration, likely via the use of the `WP_Scripts->add_data()` method, currently found in source [at this location](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-dependencies.php#L288), and possibly via this method being called by either `wp_register_script` or `wp_enqueue_script` functions.
* The method is to accept the following function parameters:
	* `$handle` (string) - A string reference to the registered script handle for which data is being normalized.
* The method should check for legacy `bool` values from the previous `$in_footer` implementation during script registration, as well as the new `$args` implementation during script registration in order to determine a `in_footer` value of `true/false`. See the following issues for an understanding of the new `$args` parameter:
	* https://github.com/10up/wordpress-develop/issues/9
	* https://github.com/10up/wordpress-develop/issues/8
* The method should check for usage of the new `$args` parameter to determine the intended loading strategy, and return the necessary string value in said array key.
* This method should return the following array shape:
	
	```
	'in_footer' => true/false,
	'strategy'  => 'blocking|defer|async',
	```

### Unit Tests

- No tests currently exist for this method, and will need to be added.
- Tests should be created in the `Tests_Dependencies_Scripts` class, currently located at [this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L12) at the time of writing.
- The test should validate that legacy and newer implementations of registering scripts via `wp_register_script` and `wp_enqueue_script` functions (`$in_footer` vs `$args`) result in the consistent return format as indicated in the Acceptance Criteria above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
Re bullet 4:

> The method is to accept the following function parameters

Is this missing a second param for the `in_footer` value, or is it supposed to get that value from a private property of the class?

Also, I'd suggest that we don't name this method after the legacy "in_footer" arg name, and instead name it after the updated arg name to be future compatible if other args end up being added to this normalization routine in the future.

**Comment by 10upsimon** [comment]
@joemcgill 

> Is this missing a second param for the in_footer value, or is it supposed to get that value from a private property of the class?


It is not missing a property, no, as it is intended to get the `in_footer` intended value from the registered script object using the handle passed to this method.

As for naming, I am fairly impartial, would you feel more comfortable with a name such as `_wp_normalize_script_args`? This will need to be updated in a few areas (Design Doc, task sheet etc) cc @felixarntz @adamsilverstein 

@joemcgill I've also added a Unit Tests sub heading under the AC heading for this issue.

**Comment by joemcgill** [comment]
Thanks for clarifying how the method is intended to work. I like your naming suggestion. Alternately, if the method is just returning a normalized set of args and not mutating the properties of the script object itself, `_wp_get_normalized_script_args()` may be more descriptive.

**Comment by felixarntz** [comment]
@10upsimon @joemcgill Either of the two names would work for me, just would like to avoid the `_` prefix to that method; underscore-prefixed methods to indicate private access are not a great pattern; since this would be a class method, it could be technically made private anyway, but even if it was a function, we should avoid the `_` prefix and rather just rely on an `@access private` annotation.

@10upsimon I don't think it's critical to keep updating the design doc with e.g. function renames like this. It's natural that as part of implementation some details may change, and I think in the long run it would create lots of overhead that's probably not worth justifying if we "backported" every single implementation change to the original design doc.

**Comment by 10upsimon** [comment]
@felixarntz  @joemcgill  points taken (all fair) and I am settling on `wp_get_normalized_script_args()`

**Comment by 10upsimon** [comment]
@joemcgill given that the remaining feedback was centred around the naming convention of the function, and we all agreed on 1 or 2 names, I am moving this to To Do, as I have renamed the method. I will update other issues that reference the same name.

**Comment by felixarntz** [comment]
@10upsimon Wait, are we talking about a (global) function or about a (class) method? Just to clarify, only if it's a function it should have the `wp_` prefix.

**Comment by kt-12** [comment]
@10upsimon @felixarntz  @joemcgill  I feel we need to drop 'wp_' from the function name. All the functions inside "WP_Scripts" is in Verb_Noun format.

**Comment by joemcgill** [comment]
I agree @kt-12. I agree that we can drop the `wp_` prefixes from method names inside classes. The `wp_` prefix should only be needed for non-class functions.
