### ISSUE TITLE
Amend script registration logic to digest normalized `$in_footer` and `$args` parameter data returned by `_wp_normalize_script_in_footer_args()` and store it against the script instance

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#11]
## Description
With the finalisation of the `_wp_normalize_script_in_footer_args()` method implementation (https://github.com/10up/wordpress-develop/issues/10), the script registration process (by way of the `wp_register_script` or `wp_enqueue_script` functions) should be updated to utilize data returned from this normalization method, and store said data agains the registered script object using the `WP_Scripts->add_data()` method.

## Acceptance Criteria

* Enhance the existing script registration logic employed by the `wp_register_script` and `wp_enqueue_script` functions, namely the `WP_Scripts()->add_data()` method, currently [located here](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-dependencies.php#L288) in WordPress source, to ensure that normalized data is retrieved using the new `_wp_normalize_script_in_footer_args()` method, and stored against the registered script object at the time of registration.
* Ensure that further methods called or class instantiationssuch as `new _WP_Dependency()` correctly forward said normalized data so that it's storage against the script object in question is eventual and guaranteed.
* Following execution of the above, the normalized array of data should be visibly stored agains the script object when inpsecting it.

### Unit Tests

- Existing tests for WP_Scripts API operations reside in the `Tests_Dependencies_Scripts` class, currently located at [this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L12) at the time of writing.
- Tests should be added that assert that data stored against the registered script object when using the legacy `$in_footer` approach and new `$args` approach result in a consistent data pattern as per the Acceptance Criteria of this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
Is the first bullet in the AC is meant to say `WP_Scripts()->add_data()` rather than `WP_Scripts()->add()` based on the description?

**Comment by 10upsimon** [comment]
@joemcgill eagle eyes! good catch, yes I meant `add_data()`. Will amend shortly.

**Comment by 10upsimon** [comment]
@joemcgill noting that pending the outcome of the discussion WRT the naming of `_wp_noramlize_script_in_footer_args`, this and tests relating to it may need wording changed. Have noted this down to finalize pending the outcome.

**Comment by 10upsimon** [comment]
@joemcgill  I've also added a Unit Tests section as a sub heading of the AC

**Comment by joemcgill** [comment]
All good. Thanks!
