### ISSUE TITLE
Implement new `get_eligible_loading_strategy()` method

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#12]
## Description
With the finalisation of the `wp_get_normalized_script_args()` method implementation #10 , including the the script registration process having been updated (see issues [9](https://github.com/10up/wordpress-develop/issues/9) and [8](https://github.com/10up/wordpress-develop/issues/8)), the `get_eligible_loading_strategy()` method can be introduced to the `WP_Scripts` class/API. The current `WP_Scripts` API resides in source [at this location](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-scripts.php).

**NOTE:** This issue does not require implementation of actual logic within this new `get_eligible_loading_strategy()`, it merely requires introduction of the method in the applicable areas within WP_Scripts API. Actual implementation logic is outlined in #13 (including return types).

## Acceptance Criteria

* Create new `get_eligible_loading_strategy()` method within the existing [WP_Scripts](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-scripts.php) class.
* Method to be private as only utilize during script registration process (or prior to printing) in order to gauge most eligible loading strategy.
* Method to accept one parameter, `$handle` (string), which is the string identifier of an already registered script handle. Defaults to `''`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
It's not clear from the current acceptance criteria what the `get_eligible_loading_strategy()` method should return. Could that be added here? Also, this implementation should come with new PHPUnit tests.

[Update] I didn't realize when I made this comment that all the business logic is meant to be implemented in issue #13.

**Comment by 10upsimon** [comment]
@joemcgill your comment is still fair, as perhaps this needs to be made cleared in the ticket. I will update it so that it is more obvious that actual logic of the method is added in #13

**Comment by 10upsimon** [comment]
@joemcgill I've updated the description to make it clearer that the meat of this work us defined in #13 

Moving this over to To Do. if you disagree, please move it back and I will iterate further.

**Comment by 10upsimon** [comment]
@joemcgill I just saw your response in #13 after replying here. I think maybe we can bundle the two actually, that is probably a better idea.
