### ISSUE TITLE
Update existing script `do_item` outputting functionality to add `defer` or `async` attributes to script tag

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#14]
## Description
With the implementation of the `get_eligible_loading_strategy()` method within the `WP_Scripts` class ([see issue here](https://github.com/10up/wordpress-develop/issues/13)), and its full implementation/business logic having been introduced, the existing `do_item()` method (and applicable associated logic) should be enhanced in order to successfully apply the loading strategy attribute to the printed `<script>` tag.

The existing `do_item()` method can be found within the `WP_Scripts` API [at this location](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/class-wp-scripts.php#L261-L415) within the current WordPress source.

Currently, the `do_item()` method creates an object that references the script object in question, and it is derived from the classes registered property.The logic further goes on to utilize various properties of said script object in order to perform various aspects of the output process. 

Logic introduced as a result of this issue should ensure that `do_item()` be expanded upon to check for the presence of any attribute key value pairs added to objects extra property, such as a strategy, and handle the output of the `<script>` tag correctly, adding the necessary loading attribute to said `<script>` tag.

## Acceptance Criteria

* Enhancement to the existing `do_item()` method to ensure that loading strategies stored against a script object are successfully output as part of the script printing process.
* Work carried out within any other necessary method(s) utilized by `do_item()` in order to achieve the above.
* Upon completion of the work, scripts eligible for a loading strategy should begin printing said loading strategy attribute in their `<script>` tag, one of:
	* `defer`
	* `async`
* Scripts should be confirmed as having been loaded by the browser using the applicable strategy as above.

### Unit Tests
* Unit tests for the various processes script and script dependency logic currently reside in WordPress core source  [at this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php).
* Applicable tests should be added (or existing tests modified) that assert that scripts eligible for an `async` strategy contain the `async` loading strategy attribute on the printed `<script>` tag.
* Applicable tests should be added (or existing tests modified) that assert that scripts eligible for a `defer` strategy contain the `defer` loading strategy attribute on the printed `<script>` tag.
* Applicable tests should be added (or existing tests modified) that assert that scripts with a blocking (default) strategy contain no loading strategy attribute on the printed `<script>` tag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
This looks good. Only suggestion is that we ensure this functionality also adds related PHPUnit tests that confirm this behavior.

**Comment by 10upsimon** [comment]
@joemcgill I've added some unit test pointers to this issue.

**Comment by joemcgill** [comment]
I just left a not about having unit test that cover the `get_eligible_loading_strategy` method to #13, but this is likely the place to do it. Would it also make sense to add a test case that ensures recursive loops are handled appropriately as explained in #13 as well?

**Comment by 10upsimon** [comment]
@joemcgill are you specifically referring to us testing for _not_ introducing recursive loops? We do not change the dependencies (only their strategies) so I am not sure we can actually introduce a recursive loop here. WordPress also does not handle recursive loops in terms of dependencies.

Are we on the same page or do you feel I have missed something important here?

**Comment by joemcgill** [comment]
Correct, I was suggesting that we have a test to to confirm this requirement that is listed in #13:

> Method is to be recursive in nature and check all dependents and dependency scripts of a given handle, but should be written in a way that it never enters into an infinite loop.

If we are able to write a unit test that confirm that this method doesn't enter an infinite loop, I think that would be useful.

**Comment by 10upsimon** [comment]
Thanks @joemcgill , agreed. I am going to expand the test suite in #13 to cater for this, and in fact it needs the addition of the test suite as there currently is none. I think that will take care of the outstanding tests, as the ones specific to this issue are already outlined herein.

Moving this specific one to To Do as a result of updating #13 with tests instead, feel free to move back to AC Review if you disagree @joemcgill
