### ISSUE TITLE
Update the `wp_add_inline_script` function to provide a means for specifying an inline script as being standalone

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#15]
## Description
As part of enhancing the Scripts API with a loading strategy, there is a requirement to correctly handle inline scripts attached to main scripts so that their execution order is maintained. Inline scripts may, however, want to remain totally strategy agnostic and function in a standalone mode, having no inherent need to obey any parent/main script loading strategies. In order to provide this functionality, inline scripts should be able to specify/opt in to a standalone mode. 

The existing `wp_add_inline_script` method, currently residing in WordPress core source [at this location](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/functions.wp-scripts.php#L130-L148), should therefore be updated to cater for this new requirement. It should achieve this by way of introducing a new `$standalone` parameter to the function. This `boolean` parameter will be used to determine whether a user has opted for said inline script to be `$standalone` or not.

## Acceptance Criteria

* Enhancement to the existing `wp_add_inline_script` method, allowing the specification of a `boolean` value against a new `$standalone` parameter. This method currently resides in WordPress core source [at this location](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/functions.wp-scripts.php#L130-L148).
	* Addition of a new `$standalone` parameter to said above function.
	* The `$standalone` parameter is to be of type `boolean`
	* The `$standalone` parameter is to have a default value of `false`

### Unit Tests
* Unit tests for the various processes surrounding `wp_add_inline_script` method currently reside in WordPress core source, starting [at this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L395).
* Applicable tests should be added that assert that the values of `$standalone` are of type `boolean`.
* Applicable tests should be added that assert that the default value of `$standalone` is `false`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eclarke1** [comment]
@10upsimon I notice this one is in To Do, but there's no comments relating to AC approval? Is it correct that it is ready to be worked on?
cc @joemcgill
