### ISSUE TITLE
Update `WP_Script` logic surrounding `wp_add_inline_script` function to handle standalone vs non standalone logic.

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#19]
## Description
As per [issue 15](https://github.com/10up/wordpress-develop/issues/15) where a means to opt in a script as standalone has been introduced, logic within the [WP_Scripts](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-scripts.php) class that handle the printing of inline scripts should be amended so that any inline script that specifies a $standalone = true approach bypasses all further logic that determines its parents load handler, `type="module"` etc.

## Acceptance Criteria

* Enhance the existing [WP_Scripts](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/class-wp-scripts.php) class in areas that handle inline script preparation and printing to ensure that if an inline script is opted in as standalone (see [issue 15](https://github.com/10up/wordpress-develop/issues/15)), it bypasses all further loading strategy checks, is specified as standalone in its data/properties, and is printed as blocking in whichever position it was specified for: `before` or `after`.

### Unit Tests
* Unit tests for the various processes surrounding `wp_add_inline_script` method currently reside in WordPress core source, starting [at this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L395).
* Add/edit the necessary unit tests to ensure that inline scripts that are marked as standalone are void of further loading strategy logic checks and printed in the location specified. Tests should include inline scripts associated with deferred and non deferred parent/main scripts in order to validate the business logic.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
This one seems good to me 👍 and maybe should be implemented first, before tackling the more complex logic  for dependency/loading strategy management.
