### ISSUE TITLE
Update/add core documentation for `get_eligible_loading_strategy()` method

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#22]
## Description
An important aspect of the script strategy work is to maintain correct documentation around changes to the WP_Scripts API so that developers understand fully the changes and additions that have been made to the API and how to make use of them.

With the introduction and implementation of the new `get_eligible_loading_strategy()` method, see issue #13, there is an inherent need to introduce/update new documentation to the WordPress Developer Resources suite of docs, specifically Code Reference, however, this should be automatically updated.

It should be discussed whether the Scripts API needs to be listed as a standalone API within "Common API's Handbook" at https://developer.wordpress.org/apis/ and if so, issues specific thereto should be opened.

As part of the broader release of the loading strategy work, one or more make/core blog posts will need to be published that cover the new and altered sections of the WP_Scripts API in enough detail that communicates how the entire feature works from a technical standpoint, as well as how to use it to its fullest intent. Therefore, part of these documentation efforts should involve noting down a series of technical and informative pointes that capture the essence of what the `get_eligible_loading_strategy` method does, where it is used and how it is influence by developer input within the broader sense of the script loading strategy implementation. 

## Acceptance Criteria

* Ensure that, following release into core, there is a correct reference to the new `get_eligible_loading_strategy()` method/function in the developer reference docs at https://developer.wordpress.org/reference/
* Note any auxiliary information that should be present on said documentation page that may not form part of the information gathered automatically from source
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

### Unit Tests
* N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
The developer reference docs are updated from the source code on every release, so the AC here should happen automatically. However, we may want to add some additional info to those docs. Regardless way, we wouldn't be able to add to those docs until after they are included in a release, unless I am mistaken.

The suggestion that Scripts API be added to the Common API's Handbook is an interesting one, which maybe should be brought to the Core Docs team for consideration. In the meantime, the main documentation for these APIs seem to be included in the Theme Handbook here: https://developer.wordpress.org/themes/basics/including-css-javascript/

**Comment by 10upsimon** [comment]
Closing out as the ticket definition and AC has been moved to the catchall documentation ticket at https://github.com/10up/wordpress-develop/issues/29
