### ISSUE TITLE
Documentation - Inline (Automated) & Community

### ISSUE THREAD

**Issue by 10upsimon** [10up/wordpress-develop#29]
## Description
An important aspect of the script strategy work is to maintain correct documentation around changes to the WP_Scripts API so that developers understand fully the changes and additions that have been made to the API and how to make use of them.

Documentation needs to be accounted for in the following areas:

- Automated documentation in the form of the [WordPress Developer Reference](https://developer.wordpress.org/reference/)
- Auxiliary/additional documentation efforts within the above that may be applicable, i.e extra documentation snippets added to the automated documentation above
- Series of make/core blog posts supporting and describing the work contained within the *Enhancing the Scripts API with a loading strategy* epic
- Supporting notes/devnotes required for Trac ticket(s) relating to this release of work produced within this epic

### Automated Documentation
Automated documentation should be just that - automatic - and produced from the new and updated Docblocks of functions/methods effected by the work contained in the *Enhancing the Scripts API with a loading strategy* epic. While this is automated, documentation should be verified once the feature(s) reach a core release. 

Areas affected and that should be verified are as follows:

- `wp_get_normalized_script_args()` See issue #10
- `wp_register_script` See issue #9
- `wp_enqueue_script` See issue #8
- `wp_add_inline_script` See issue #19
- `get_eligible_loading_strategy()` See issue #13  
- The `WP_Scripts` and `WP_Dependencies` class in general, and where applicable

### Auxiliary Documentation
Auxiliary documentation refers to any "extra" non automated documentation that may appear within the above documentation pages. A good example is the `wp_register_script` [reference page](https://developer.wordpress.org/reference/functions/wp_register_script/) which contains supporting information. 

As part of ongoing work within this epic, and as work is executed, engineers should be making pointers of what such information may need to appear for said reference page(s). 

### Make/Core Blog Posts (Incl. Devnotes)
As we near the delivery phase of work contained in this epic, and even at earlier stages, it is going to be necessary to release make/core blog posts that describe and/or introduce features, as well as technical notes on how they function. These should be collated at a high level, or at least capture in the form of local devnotes, so that supporting materials are readily available when it comes to drafting said posts.

### Trac Ticket Notes
Closer to the actual release of work in this epic, it is going to be necessary to add/update Trac tickets that support the merge request of this work into core.

Ongoing notes and devnotes should be captured by engineers to ensure that there is sufficient information that accurately describes the feature(s) we are releasing from both a technical and functional standpoint.

#### `wp_get_normalized_script_args()`
* Ensure that, following release into core, there is a correct reference to the new `wp_get_normalized_script_args()` method/function in the developer reference docs at https://developer.wordpress.org/reference/
* Note any auxiliary information that should be present on said documentation page that may not form part of the information gathered automatically from source
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

#### `wp_register_script`
* Ensure that, following release into core, there is a correct reference to the new $args parameter for the  `wp_register_script`function in the developer reference docs at [https://developer.wordpress.org/reference/functions/wp_register_script/](https://developer.wordpress.org/reference/functions/wp_register_script/)
* Ensure that auxiliary information at said resource is updated to reflect, where applicable, any supporting docs or blocks posts surrounding the Script Loading Strategy.
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

#### `wp_enqueue_script`
* Ensure that, following release into core, there is a correct reference to the new $args parameter for the  `wp_register_script`function in the developer reference docs at [https://developer.wordpress.org/reference/functions/wp_enqueue_script/](https://developer.wordpress.org/reference/functions/wp_enqueue_script/)
* Ensure that auxiliary information at said resource is updated to reflect, where applicable, any supporting docs or blocks posts surrounding the Script Loading Strategy.
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

#### `get_eligible_loading_strategy()`
* Ensure that, following release into core, there is a correct reference to the new `get_eligible_loading_strategy()` method/function in the developer reference docs at [https://developer.wordpress.org/reference/functions/wp_register_script/](https://developer.wordpress.org/reference/functions/wp_register_script/)
* Ensure that auxiliary information at said resource is updated to reflect, where applicable, any supporting docs or blocks posts surrounding the Script Loading Strategy.
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

#### `wp_add_inline_script`
* Ensure that, following release into core, there is a correct reference to the new $args parameter for the  `wp_add_inline_script `function in the developer reference docs at [https://developer.wordpress.org/reference/functions/wp_add_inline_script/](https://developer.wordpress.org/reference/functions/wp_add_inline_script/)
* Ensure that auxiliary information at said resource is updated to reflect, where applicable, any supporting docs or blocks posts surrounding the Script Loading Strategy.
* Create pointers and notes that support easy addition to future make/core blog posts in order for this method to be fully communicated to the community from a technical standpoint.

#### Ongoing devnotes and technical pointers capturing
- Engineers involved in work within any aspect of this epic should capture technical DEVNOTE style pointers that support the work carried out by said issue(s). These can be captured externally, but should be shared here as the time to collaborate with other core documentation teams arises.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
Thanks for creating this tracking issue, @10upsimon. I think we can go ahead and close out the previous individual documentation issues in favor of this one for now.

**Comment by joemcgill** [comment]
This effort is complete.
