### ISSUE TITLE
Script Loading: Consider adding a data attribute which specifically contains the handle

### ISSUE THREAD

**Issue by westonruter** [10up/wordpress-develop#70]
### Is your enhancement related to a problem? Please describe.

We currently are parsing the script handle out of the `id` attribute for `script` tags. This could be made more ergonomic if we added a `data-wp-handle` attribute that only contained the handle, similar to how delayed inline scripts now get `data-wp-deps` as of #67.

Related to #68, which introduces `data-wp-strategy`. 

Note that the attributes may need to be added _after_ the `script_loader_tag` filter applies, so as to ensure they are always present. Otherwise they could break our delayed-inline-script-loader logic.

cf. https://github.com/10up/wordpress-develop/pull/67/files#r1213241271 and https://github.com/10up/wordpress-develop/pull/67/files#r1213705552

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
Unless I'm mistaken, this is primarily helpful only if we're trying to match dependencies with handles in JS for delaying inline scripts. Given that delayed inline scripts have been removed in #81, this is not currently needed. I'm going to close it for now and we can reconsider if adding support for delayed inline scripts is reinstated.
