### ISSUE TITLE
Update `wp_enqueue_script` function to support addition of `$args` parameter as reimplementation of the `$in_footer` parameter

### ISSUE THREAD

**Issue by eclarke1** [10up/wordpress-develop#8]
## Description
The existing `wp_enqueue_script` function requires modification to overload the current `$in_footer` parameter with the newly proposed $args parameter, that will now accept an array of data, as opposed to the current boolean type. Backward compatibility is not affected by this change.

## Acceptance Criteria

* The existing `wp_enqueue_script` function within `WP_Scripts` class is modified and the new `$args` parameter is introduced by overloading the current `$in_footer` parameter. The existing function can be found in WordPress core [at this location](https://github.com/WordPress/WordPress/blob/6.1-branch/wp-includes/functions.wp-scripts.php#L346).
* The `$args` parameter is to default to an empty array.
* The docblock for said preexisting `wp_enqueue_script` function is to be updated to reflect the type and shape of the `$args` parameter, and is to document the following array structure in the correct docblock formatting as per WordPress documentation standards:
 * `in_footer` (bool) default `false` - Functions in the same manner as the prior `$in_footer` arg and dictates whether the script should be loaded in the footer or not (assuming it has a blocking loading strategy)
 * `strategy` (string) default `'blocking'` - Accepts a string that identifies the intended loading strategy of said script, is one of the following:
	  * `'blocking'` - Indicates that the scripts loading strategy should be that of a blocking one, i.e not `'defer'` or `'async'`
	  * `'defer'` - Indicates that the scripts loading strategy is intended to be `defer`.
	  * `'async'` - Indicates that the scripts loading strategy is intended to be `async`.

### Unit Tests

- Existing tests that cover the `wp_enqueue_script` function reside in the `Tests_Dependencies_Scripts` class, currently located at [this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L12) at the time of writing.
- The test method in question for this function is `test_wp_enqueue_script` and resides at [this location](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/dependencies/scripts.php#L48) at the time of writing. 
- This method should be updated accordingly to support both the legacy `$in_footer` implementation and new `$args` implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joemcgill** [comment]
Also include unit tests, in applicable. Same as the comment in #9

**Comment by 10upsimon** [comment]
Thanks @joemcgill , I've added a Unit Tests sub heading below the AC heading, please let me know if this suffices.

**Comment by joemcgill** [comment]
Thank you
